import React from 'react'
import { useState } from 'react';

function Data() {
    const [phone, setProducts] = useState([
        {
          asin: "B0BMGC6LHP",
          product_title:
            "Samsung Galaxy M04 Light Green, 4GB RAM, 128GB Storage | Upto 8GB RAM with RAM Plus | MediaTek Helio P35 Octa-core Processor | 5000 mAh Battery | 13MP Dual Camera",
          product_price: "₹7,499",
          product_original_price: "₹13,499",
          currency: "INR",
          product_star_rating: "3.9",
          product_num_ratings: 12777,
          product_url: "https://www.amazon.in/dp/B0BMGC6LHP",
          product_photo:
            "https://m.media-amazon.com/images/I/813sVzTfvaL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹7,499",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0CGX8DHM2",
          product_title: "OnePlus Nord N20 SE (Oasis Blue, 4GB RAM, 64GB Storage)",
          product_price: "₹14,499",
          product_original_price: "₹24,999",
          currency: "INR",
          product_star_rating: "5",
          product_num_ratings: 2,
          product_url: "https://www.amazon.in/dp/B0CGX8DHM2",
          product_photo:
            "https://m.media-amazon.com/images/I/61dZ+E7kndL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹14,499",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0C4622G6N",
          product_title:
            "realme narzo N53 (Feather Black, 6GB+128GB) 33W Segment Fastest Charging | Slimmest Phone in Segment | 90 Hz Smooth Display",
          product_price: "₹9,999",
          product_original_price: "₹12,999",
          currency: "INR",
          product_star_rating: "3.9",
          product_num_ratings: 8045,
          product_url: "https://www.amazon.in/dp/B0C4622G6N",
          product_photo:
            "https://m.media-amazon.com/images/I/71DSxfKzkJL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹9,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0B4F2TTTS",
          product_title:
            "Samsung Galaxy M13 (Aqua Green, 4GB, 64GB Storage) | 6000mAh Battery | Upto 8GB RAM with RAM Plus",
          product_price: "₹9,199",
          product_original_price: "₹14,999",
          currency: "INR",
          product_star_rating: "4.1",
          product_num_ratings: 28323,
          product_url: "https://www.amazon.in/dp/B0B4F2TTTS",
          product_photo:
            "https://m.media-amazon.com/images/I/81fVPmkBsIL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹9,199",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0C71JLZFB",
          product_title:
            "realme C55 (Rainforest, 6GB RAM, 64 Storage) | 6.72 inch Full HD+ Display | 64MP + 2MP | 8MP Front Camera | Helio G88 Processor | Brilliant Security | Convenient Multitasking",
          product_price: "₹10,698",
          product_original_price: "₹13,999",
          currency: "INR",
          product_star_rating: "4",
          product_num_ratings: 250,
          product_url: "https://www.amazon.in/dp/B0C71JLZFB",
          product_photo:
            "https://m.media-amazon.com/images/I/71YAkudHwHL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹10,698",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0BMGG6NKT",
          product_title:
            "Samsung Galaxy M04 Dark Blue, 4GB RAM, 128GB Storage | Upto 8GB RAM with RAM Plus | MediaTek Helio P35 Octa-core Processor | 5000 mAh Battery | 13MP Dual Camera",
          product_price: "₹7,499",
          product_original_price: "₹13,499",
          currency: "INR",
          product_star_rating: "3.9",
          product_num_ratings: 12777,
          product_url: "https://www.amazon.in/dp/B0BMGG6NKT",
          product_photo:
            "https://m.media-amazon.com/images/I/81xJ80yRRzL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹7,499",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0C45VWDWJ",
          product_title:
            "realme narzo N53 (Feather Black, 4GB+64GB) 33W Segment Fastest Charging | Slimmest Phone in Segment | 90 Hz Smooth Display",
          product_price: "₹7,999",
          product_original_price: "₹10,999",
          currency: "INR",
          product_star_rating: "3.9",
          product_num_ratings: 8045,
          product_url: "https://www.amazon.in/dp/B0C45VWDWJ",
          product_photo:
            "https://m.media-amazon.com/images/I/71DSxfKzkJL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹7,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0CBYV1BKH",
          product_title:
            "Nothing Phone (2) 5G (Dark Grey, 12GB RAM, 256GB Storage)",
          product_price: "₹44,949",
          product_original_price: "₹54,999",
          currency: "INR",
          product_star_rating: "3.6",
          product_num_ratings: 23,
          product_url: "https://www.amazon.in/dp/B0CBYV1BKH",
          product_photo:
            "https://m.media-amazon.com/images/I/713rQyFyeXL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹44,949",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0B9YK24TF",
          product_title:
            "Nokia 2660 Flip 4G Volte keypad Phone with Dual SIM, Dual Screen, inbuilt MP3 Player &amp; Wireless FM Radio | Black",
          product_price: "₹4,449",
          product_original_price: "₹5,899",
          currency: "INR",
          product_star_rating: "3.8",
          product_num_ratings: 2734,
          product_url: "https://www.amazon.in/dp/B0B9YK24TF",
          product_photo:
            "https://m.media-amazon.com/images/I/61RBrScYUSL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹4,449",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0B4F52B5X",
          product_title:
            "Samsung Galaxy M13 (Midnight Blue, 4GB, 64GB Storage) | 6000mAh Battery | Upto 8GB RAM with RAM Plus",
          product_price: "₹9,199",
          product_original_price: "₹14,999",
          currency: "INR",
          product_star_rating: "4.1",
          product_num_ratings: 28323,
          product_url: "https://www.amazon.in/dp/B0B4F52B5X",
          product_photo:
            "https://m.media-amazon.com/images/I/81PcAHZxgLL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹9,199",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B09LHYZ3GJ",
          product_title:
            "Redmi Note 11T 5G (Matte Black, 6GB RAM, 128GB ROM)| Dimensity 810 5G | 33W Pro Fast Charging | Charger Included | Additional Exchange Offers",
          product_price: "₹14,499",
          product_original_price: "₹20,999",
          currency: "INR",
          product_star_rating: "4.1",
          product_num_ratings: 35281,
          product_url: "https://www.amazon.in/dp/B09LHYZ3GJ",
          product_photo:
            "https://m.media-amazon.com/images/I/7155Pasn1aL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹14,499",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0C74PD9VG",
          product_title: "Redmi A2 (Sea Green, 2GB RAM, 64GB Storage)",
          product_price: "₹5,299",
          product_original_price: "₹9,999",
          currency: "INR",
          product_star_rating: "3.8",
          product_num_ratings: 4273,
          product_url: "https://www.amazon.in/dp/B0C74PD9VG",
          product_photo:
            "https://m.media-amazon.com/images/I/81bh6SxXQ+L._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹5,299",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B09Y64H8VS",
          product_title:
            "Xiaomi Redmi 10 Power (Power Black, 8GB RAM, 128GB Storage)",
          product_price: "₹10,649",
          product_original_price: "₹18,999",
          currency: "INR",
          product_star_rating: "4.1",
          product_num_ratings: 3734,
          product_url: "https://www.amazon.in/dp/B09Y64H8VS",
          product_photo:
            "https://m.media-amazon.com/images/I/71BiCb7N5YL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹10,649",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0C591VB5D",
          product_title:
            "Nokia C32 with 50MP Dual Rear AI Camera | Toughened Glass Back | 4GB RAM, 128GB Storage | Upto 7GB RAM with RAM Extension | 5000 mAh Battery | 1 Year Replacement Warranty | Android 13 | Pink",
          product_price: "₹8,999",
          product_original_price: "₹10,999",
          currency: "INR",
          product_star_rating: "3.6",
          product_num_ratings: 447,
          product_url: "https://www.amazon.in/dp/B0C591VB5D",
          product_photo:
            "https://m.media-amazon.com/images/I/615ay8KozlL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹8,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
    
        {
          asin: "B09Y64H8VS",
          product_title:
            "Xiaomi Redmi 10 Power (Power Black, 8GB RAM, 128GB Storage)",
          product_price: "₹10,649",
          product_original_price: "₹18,999",
          currency: "INR",
          product_star_rating: "4.1",
          product_num_ratings: 3739,
          product_url: "https://www.amazon.in/dp/B09Y64H8VS",
          product_photo:
            "https://m.media-amazon.com/images/I/71BiCb7N5YL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹10,649",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0C591VB5D",
          product_title:
            "Nokia C32 with 50MP Dual Rear AI Camera | Toughened Glass Back | 4GB RAM, 128GB Storage | Upto 7GB RAM with RAM Extension | 5000 mAh Battery | 1 Year Replacement Warranty | Android 13 | Pink",
          product_price: "₹8,999",
          product_original_price: "₹10,999",
          currency: "INR",
          product_star_rating: "3.6",
          product_num_ratings: 446,
          product_url: "https://www.amazon.in/dp/B0C591VB5D",
          product_photo:
            "https://m.media-amazon.com/images/I/615ay8KozlL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹8,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0BBM78DMV",
          product_title:
            "realme narzo 50i Prime (Mint Green 4GB RAM+64GB Storage) Octa-core Processor |5000 mAh Battery",
          product_price: "₹7,299",
          product_original_price: "₹9,999",
          currency: "INR",
          product_star_rating: "4",
          product_num_ratings: 7333,
          product_url: "https://www.amazon.in/dp/B0BBM78DMV",
          product_photo:
            "https://m.media-amazon.com/images/I/819bwF7gjfL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹7,299",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0B4F2XCK3",
          product_title:
            "Samsung Galaxy M13 (Aqua Green, 6GB, 128GB Storage) | 6000mAh Battery | Upto 12GB RAM with RAM Plus",
          product_price: "₹11,499",
          product_original_price: "₹17,999",
          currency: "INR",
          product_star_rating: "4.1",
          product_num_ratings: 28355,
          product_url: "https://www.amazon.in/dp/B0B4F2XCK3",
          product_photo:
            "https://m.media-amazon.com/images/I/81fVPmkBsIL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹11,499",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0C46GD5V7",
          product_title:
            "Redmi A2 (Aqua Blue, 4GB RAM, 64GB Storage) | Powerful Octa Core G36 Processor | Upto 7GB RAM | Large 16.5 cm HD+ Display with Massive 5000mAh Battery | 2 Years Warranty [Limited time Offer]",
          product_price: "₹6,799",
          product_original_price: "₹10,999",
          currency: "INR",
          product_star_rating: "3.8",
          product_num_ratings: 4289,
          product_url: "https://www.amazon.in/dp/B0C46GD5V7",
          product_photo:
            "https://m.media-amazon.com/images/I/81RR0TAz+5L._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹6,799",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0C8VWNQBF",
          product_title:
            "Itel A60s (4GB RAM + 64GB ROM, Up to 8GB RAM with Memory Fusion | 8MP AI Rear Camera | 5000mAh Battery with 10W Charging | Faceunlock &amp; Fingerprint -Glacier Green",
          product_price: "₹5,999",
          product_original_price: "₹8,499",
          currency: "INR",
          product_star_rating: "3.7",
          product_num_ratings: 367,
          product_url: "https://www.amazon.in/dp/B0C8VWNQBF",
          product_photo:
            "https://m.media-amazon.com/images/I/71LtFZN0-7L._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹5,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0C787GXXR",
          product_title:
            "realme narzo 60 Pro (Cosmic Black,12GB+1TB) Ultra Smooth 120 Hz Super Amoled Curved Display | 100 MP OIS Camera",
          product_price: "₹26,999",
          product_original_price: "₹32,999",
          currency: "INR",
          product_star_rating: "4",
          product_num_ratings: 1191,
          product_url: "https://www.amazon.in/dp/B0C787GXXR",
          product_photo:
            "https://m.media-amazon.com/images/I/81ZV6G2iRrL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹26,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0BBM7L888",
          product_title:
            "realme narzo 50i Prime (Dark Blue 4GB RAM+64GB Storage) Octa-core Processor | 5000 mAh Battery",
          product_price: "₹7,299",
          product_original_price: "₹9,999",
          currency: "INR",
          product_star_rating: "4",
          product_num_ratings: 7333,
          product_url: "https://www.amazon.in/dp/B0BBM7L888",
          product_photo:
            "https://m.media-amazon.com/images/I/81WPIz1l5wL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹7,299",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B09RMN7HY3",
          product_title:
            "realme narzo 50 (Speed Black, 6GB RAM+128GB Storage) Helio G96 Processor | 50MP AI Triple Camera | 120Hz Ultra Smooth Display",
          product_price: "₹12,899",
          product_original_price: "₹17,999",
          currency: "INR",
          product_star_rating: "4.2",
          product_num_ratings: 18529,
          product_url: "https://www.amazon.in/dp/B09RMN7HY3",
          product_photo:
            "https://m.media-amazon.com/images/I/81X85GWtYHL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹12,899",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B07WGPKTST",
          product_title:
            "Vivo Y27 (Burgundy Black, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers",
          product_price: "₹13,999",
          product_original_price: "₹18,999",
          currency: "INR",
          product_star_rating: "4.1",
          product_num_ratings: 78,
          product_url: "https://www.amazon.in/dp/B07WGPKTST",
          product_photo:
            "https://m.media-amazon.com/images/I/61gdyDHr9ZL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹13,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0BZ48H8JX",
          product_title:
            "realme narzo N55 (Prime Black, 6GB+128GB) 33W Segment Fastest Charging | Super High-res 64MP Primary AI Camera",
          product_price: "₹12,999",
          product_original_price: "₹14,999",
          currency: "INR",
          product_star_rating: "4",
          product_num_ratings: 8596,
          product_url: "https://www.amazon.in/dp/B0BZ48H8JX",
          product_photo:
            "https://m.media-amazon.com/images/I/81ogvU1j6qL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹12,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0CHJPZXX5",
          product_title:
            "itel P55 5G | Dimensity 6080 | 12GB* RAM+128GB ROM with Memory Fusion| 50MP AI Dual Rear Camera| 5000mAh Battery | 2 Years Warranty | Galaxy Blue",
          product_price: "₹9,999",
          product_original_price: "₹13,599",
          currency: "INR",
          product_star_rating: "4.4",
          product_num_ratings: 200,
          product_url: "https://www.amazon.in/dp/B0CHJPZXX5",
          product_photo:
            "https://m.media-amazon.com/images/I/81jXL12hXYL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹9,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0C9JD8324",
          product_title: "Redmi 12 5G Pastel Blue 4GB RAM 128GB ROM",
          product_price: "₹11,999",
          product_original_price: "₹15,999",
          currency: "INR",
          product_star_rating: "3.8",
          product_num_ratings: 3085,
          product_url: "https://www.amazon.in/dp/B0C9JD8324",
          product_photo:
            "https://m.media-amazon.com/images/I/71UIZHHo5hL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹11,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0BQ3Q5NDH",
          product_title:
            "Redmi Note 12 5G Frosted Green 6GB RAM 128GB ROM | 1st Phone with 120Hz Super AMOLED and Snapdragon® 4 Gen 1 | 48MP AI Triple Camera",
          product_price: "₹17,499",
          product_original_price: "₹21,999",
          currency: "INR",
          product_star_rating: "3.8",
          product_num_ratings: 8149,
          product_url: "https://www.amazon.in/dp/B0BQ3Q5NDH",
          product_photo:
            "https://m.media-amazon.com/images/I/81sTK4zipDL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹17,499",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B09WQY65HN",
          product_title:
            "OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM, 128GB Storage)",
          product_price: "₹17,999",
          product_original_price: "₹19,999",
          currency: "INR",
          product_star_rating: "4.2",
          product_num_ratings: 137854,
          product_url: "https://www.amazon.in/dp/B09WQY65HN",
          product_photo:
            "https://m.media-amazon.com/images/I/61K7ujVUm+L._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹17,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0BMGB2TPR",
          product_title:
            "Samsung Galaxy M04 Light Green, 4GB RAM, 64GB Storage | Upto 8GB RAM with RAM Plus | MediaTek Helio P35 Octa-core Processor | 5000 mAh Battery | 13MP Dual Camera",
          product_price: "₹6,999",
          product_original_price: "₹11,499",
          currency: "INR",
          product_star_rating: "3.9",
          product_num_ratings: 12825,
          product_url: "https://www.amazon.in/dp/B0BMGB2TPR",
          product_photo:
            "https://m.media-amazon.com/images/I/813sVzTfvaL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹6,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0BMGB3CH9",
          product_title:
            "Samsung Galaxy M04 Dark Blue, 4GB RAM, 64GB Storage | Upto 8GB RAM with RAM Plus | MediaTek Helio P35 Octa-core Processor | 5000 mAh Battery | 13MP Dual Camera",
          product_price: "₹6,999",
          product_original_price: "₹11,999",
          currency: "INR",
          product_star_rating: "3.9",
          product_num_ratings: 12825,
          product_url: "https://www.amazon.in/dp/B0BMGB3CH9",
          product_photo:
            "https://m.media-amazon.com/images/I/81xJ80yRRzL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹6,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0CGDQ9SN7",
          product_title:
            "realme narzo 60X 5G（Stellar Green, 4GB, 128GB Storage） Up to 2TB External Memory | 50 MP AI Primary Camera | Segments only 33W Supervooc Charge",
          product_price: "₹12,249",
          product_original_price: "₹14,999",
          currency: "INR",
          product_star_rating: "4",
          product_num_ratings: 822,
          product_url: "https://www.amazon.in/dp/B0CGDQ9SN7",
          product_photo:
            "https://m.media-amazon.com/images/I/81WimZLWH1L._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹12,249",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0BQ3RC28F",
          product_title:
            "Redmi Note 12 5G Frosted Green 4GB RAM 128GB ROM | 1st Phone with 120Hz Super AMOLED and Snapdragon® 4 Gen 1 | 48MP AI Triple Camera",
          product_price: "₹15,998",
          product_original_price: "₹19,999",
          currency: "INR",
          product_star_rating: "3.8",
          product_num_ratings: 8149,
          product_url: "https://www.amazon.in/dp/B0BQ3RC28F",
          product_photo:
            "https://m.media-amazon.com/images/I/81sTK4zipDL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹15,998",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0CGX8DHM2",
          product_title: "OnePlus Nord N20 SE (Oasis Blue, 4GB RAM, 64GB Storage)",
          product_price: "₹14,999",
          product_original_price: "₹24,999",
          currency: "INR",
          product_star_rating: "5",
          product_num_ratings: 2,
          product_url: "https://www.amazon.in/dp/B0CGX8DHM2",
          product_photo:
            "https://m.media-amazon.com/images/I/61dZ+E7kndL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹14,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0C786YYDW",
          product_title:
            "realme narzo 60 Pro (Cosmic Black,12GB+256GB) Ultra Smooth 120 Hz Super Amoled Curved Display | 100 MP OIS Camera",
          product_price: "₹23,999",
          product_original_price: "₹28,999",
          currency: "INR",
          product_star_rating: "4",
          product_num_ratings: 1191,
          product_url: "https://www.amazon.in/dp/B0C786YYDW",
          product_photo:
            "https://m.media-amazon.com/images/I/81ZV6G2iRrL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹23,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0B56YWX99",
          product_title:
            "TECNO Spark 9 (Infinity Black, 4GB RAM,64GB Storage) | 7GB Expandable RAM | Helio G37 Gaming Processor",
          product_price: "₹6,999",
          product_original_price: "₹11,499",
          currency: "INR",
          product_star_rating: "3.9",
          product_num_ratings: 6202,
          product_url: "https://www.amazon.in/dp/B0B56YWX99",
          product_photo:
            "https://m.media-amazon.com/images/I/9185sX9EGFL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹6,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0BBM7L888",
          product_title:
            "realme narzo 50i Prime (Dark Blue 4GB RAM+64GB Storage) Octa-core Processor | 5000 mAh Battery",
          product_price: "₹7,299",
          product_original_price: "₹9,999",
          currency: "INR",
          product_star_rating: "4",
          product_num_ratings: 7333,
          product_url: "https://www.amazon.in/dp/B0BBM7L888",
          product_photo:
            "https://m.media-amazon.com/images/I/81WPIz1l5wL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹7,299",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0CGDNJX9X",
          product_title:
            "realme narzo 60X 5G（Nebula Purple 6GB,128GB Storage ） Up to 2TB External Memory | 50 MP AI Primary Camera | Segments only 33W Supervooc Charge",
          product_price: "₹13,499",
          product_original_price: "₹15,999",
          currency: "INR",
          product_star_rating: "4",
          product_num_ratings: 822,
          product_url: "https://www.amazon.in/dp/B0CGDNJX9X",
          product_photo:
            "https://m.media-amazon.com/images/I/818UhQ1kpdL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹13,499",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0B4F2K7N1",
          product_title:
            "Samsung Galaxy M13 (Stardust Brown, 4GB, 64GB Storage) | 6000mAh Battery | Upto 8GB RAM with RAM Plus",
          product_price: "₹9,499",
          product_original_price: "₹14,999",
          currency: "INR",
          product_star_rating: "4.1",
          product_num_ratings: 28355,
          product_url: "https://www.amazon.in/dp/B0B4F2K7N1",
          product_photo:
            "https://m.media-amazon.com/images/I/81kkRZALXQL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹9,499",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B09MKNX29Z",
          product_title:
            "Redmi Note 10S (Frost White, 8GB RAM,128 GB Storage) - Super Amoled Display | 64 MP Quad Camera | Alexa Built in | 33W Charger Included",
          product_price: "₹14,749",
          product_original_price: "₹20,999",
          currency: "INR",
          product_star_rating: "4.2",
          product_num_ratings: 213796,
          product_url: "https://www.amazon.in/dp/B09MKNX29Z",
          product_photo:
            "https://m.media-amazon.com/images/I/81leb5g4asL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹14,749",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B0BYN6SGHD",
          product_title:
            "Redmi 12C (Mint Green, 6GB RAM, 128GB Storage) | High Performance Mediatek Helio G85 | Big 17cm(6.71) HD+ Display with 5000mAh(typ) Battery",
          product_price: "₹9,499",
          product_original_price: "₹15,999",
          currency: "INR",
          product_star_rating: "3.9",
          product_num_ratings: 8597,
          product_url: "https://www.amazon.in/dp/B0BYN6SGHD",
          product_photo:
            "https://m.media-amazon.com/images/I/81YEyQqHjPL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹9,499",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
        {
          asin: "B07WGPKSG8",
          product_title:
            "iQOO Z7s 5G by vivo (Pacific Night, 8GB RAM, 128GB Storage) | Ultra Bright AMOLED Display | Snapdragon 695 5G 6nm Processor | 64 MP OIS Ultra Stable Camera | 44WFlashCharge",
          product_price: "₹17,999",
          product_original_price: "₹24,999",
          currency: "INR",
          product_star_rating: "4.1",
          product_num_ratings: 10116,
          product_url: "https://www.amazon.in/dp/B07WGPKSG8",
          product_photo:
            "https://m.media-amazon.com/images/I/51oW-QOqhaL._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹17,999",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null,
        },
      ]);
  return (
    <></>
  )
}

export default Data