import React from "react";
import { useState } from "react";


function Headphone({onAddToCart }) {
  
  const [products, setProducts] = useState([

        {
          asin: "B09B5CPV71",
          product_title: "ZEBRONICS Thunder 60 hrs Playback time Bluetooth Wireless Headphone with FM, mSD, Playback with Mic (Sea Green)",
          product_price: "₹599",
          product_original_price: "₹1,399",
          currency: "INR",
          product_star_rating: "3.8",
          product_num_ratings: 63342,
          product_url: "https://www.amazon.in/dp/B09B5CPV71",
          product_photo: "https://m.media-amazon.com/images/I/61vvmibZy8L._AC_SX444_SY639_QL65_.jpg",
          product_num_offers: null,
          product_minimum_offer_price: "₹599",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: null
        },
        {
          "asin": "B07L8KNP5F",
          "product_title": "Zebronics Thunder 60 hrs Playback time Bluetooth Wireless Headphone with FM, mSD, Playback with Mic (Black)",
          "product_price": "₹599",
          "product_original_price": "₹1,399",
          "currency": "INR",
          "product_star_rating": "3.8",
          "product_num_ratings": 63342,
          "product_url": "https://www.amazon.in/dp/B07L8KNP5F",
          "product_photo": "https://m.media-amazon.com/images/I/61ImykvI9wL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹599",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B098FH5P3C",
          "product_title": "Bose Quietcomfort 45 Bluetooth Wireless Over Ear Headphones with Mic Noise Cancelling - White Smoke",
          "product_price": "₹18,988",
          "product_original_price": "₹29,900",
          "currency": "INR",
          "product_star_rating": "4.4",
          "product_num_ratings": 18226,
          "product_url": "https://www.amazon.in/dp/B098FH5P3C",
          "product_photo": "https://m.media-amazon.com/images/I/51BsejsSTqL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹18,988",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0B4G44RFS",
          "product_title": "ZEBRONICS Zeb-Storm Wired On Ear Headphone with 3.5mm Jack, Built-in Microphone for Calling, 1.5 Meter Cable, Soft Ear Cushion, Adjustable Headband, Foldable Ear Cups and Lightweight Design (Black)",
          "product_price": "₹349",
          "product_original_price": "₹799",
          "currency": "INR",
          "product_star_rating": "3.7",
          "product_num_ratings": 1039,
          "product_url": "https://www.amazon.in/dp/B0B4G44RFS",
          "product_photo": "https://m.media-amazon.com/images/I/61FrvQMXxJL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹349",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": false,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B07YNVFDK6",
          "product_title": "Zebronics Zeb-Bang Foldable Wireless BT Headphone Comes with 40mm Drivers, AUX Connectivity, Call Function, 16Hrs* Playback time &amp; Supports Voice Assistant (Green)",
          "product_price": "₹579",
          "product_original_price": "₹1,399",
          "currency": "INR",
          "product_star_rating": "3.7",
          "product_num_ratings": 9668,
          "product_url": "https://www.amazon.in/dp/B07YNVFDK6",
          "product_photo": "https://m.media-amazon.com/images/I/71MbNQcLD2L._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹579",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B01J82IYLW",
          "product_title": "boAt Rockerz 400 Bluetooth On Ear Headphones With Mic With Upto 8 Hours Playback &amp; Soft Padded Ear Cushions(Carbon Black)",
          "product_price": "₹1,099",
          "product_original_price": "₹2,990",
          "currency": "INR",
          "product_star_rating": "4.1",
          "product_num_ratings": 100311,
          "product_url": "https://www.amazon.in/dp/B01J82IYLW",
          "product_photo": "https://m.media-amazon.com/images/I/61stQYWQO4L._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹1,099",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0C5N5BCF6",
          "product_title": "Infinity - JBL Tranz 710, 72 Hrs Playtime with Quick Charge, Wireless On Ear Headphone with Mic, Deep Bass, Dual Equalizer, Bluetooth 5.0 with Voice Assistant Support (Blue)",
          "product_price": "₹1,498",
          "product_original_price": "₹4,499",
          "currency": "INR",
          "product_star_rating": "4.1",
          "product_num_ratings": 38261,
          "product_url": "https://www.amazon.in/dp/B0C5N5BCF6",
          "product_photo": "https://m.media-amazon.com/images/I/31VM4MszXiL._AC_SX290_SY416_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹1,498",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0B1PXM75C",
          "product_title": "Noise Two Wireless On-Ear Headphones with 50 Hours Playtime, Low Latency(up to 40ms), 4 Play Modes, Dual Pairing, BT v5.3 (Serene Blue)",
          "product_price": "₹1,999",
          "product_original_price": "₹4,999",
          "currency": "INR",
          "product_star_rating": "3.5",
          "product_num_ratings": 1335,
          "product_url": "https://www.amazon.in/dp/B0B1PXM75C",
          "product_photo": "https://m.media-amazon.com/images/I/517lSvEVVsL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹1,999",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B08QTYYNDN",
          "product_title": "JBL Tune 510BT, On Ear Wireless Headphones with Mic, up to 40 Hours Playtime, Pure Bass, Quick Charging, Dual Pairing, Bluetooth 5.0 &amp; Voice Assistant Support for Mobile Phones (Black)",
          "product_price": "₹2,299",
          "product_original_price": "₹4,499",
          "currency": "INR",
          "product_star_rating": "3.8",
          "product_num_ratings": 43092,
          "product_url": "https://www.amazon.in/dp/B08QTYYNDN",
          "product_photo": "https://m.media-amazon.com/images/I/61kFL7ywsZS._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹2,299",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B07KXNS51J",
          "product_title": "boAt Bassheads 162 in Ear Wired Earphones with Mic(Jazzy Blue)",
          "product_price": "₹399",
          "product_original_price": "₹1,299",
          "currency": "INR",
          "product_star_rating": "4.1",
          "product_num_ratings": 37124,
          "product_url": "https://www.amazon.in/dp/B07KXNS51J",
          "product_photo": "https://m.media-amazon.com/images/I/61nerorzssL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹399",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": false,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B096KTWHVT",
          "product_title": "Infinity by Harman Tranz 700 On Ear Wireless Headphone with Mic, 20 Hrs Playtime with Quick Charge, Deep Bass, Dual Equalizer, Bluetooth 5.0 and Voice Assistant Support (Black)",
          "product_price": "₹988",
          "product_original_price": "₹3,499",
          "currency": "INR",
          "product_star_rating": "4.1",
          "product_num_ratings": 38261,
          "product_url": "https://www.amazon.in/dp/B096KTWHVT",
          "product_photo": "https://m.media-amazon.com/images/I/61QUY1oXChS._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹988",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B01MF8MB65",
          "product_title": "boAt BassHeads 225 Special Edition in-Ear Wired Headphones with Mic (Blue)",
          "product_price": "₹499",
          "product_original_price": "₹999",
          "currency": "INR",
          "product_star_rating": "4.1",
          "product_num_ratings": 276412,
          "product_url": "https://www.amazon.in/dp/B01MF8MB65",
          "product_photo": "https://m.media-amazon.com/images/I/61fo5RouiZL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹499",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B09PV1DFNJ",
          "product_title": "ZEBRONICS Zeb-Bro in Ear Wired Earphones with Mic, 3.5mm Audio Jack, 10mm Drivers, Phone/Tablet Compatible(Red)",
          "product_price": "₹119",
          "product_original_price": "₹399",
          "currency": "INR",
          "product_star_rating": "3.5",
          "product_num_ratings": 39861,
          "product_url": "https://www.amazon.in/dp/B09PV1DFNJ",
          "product_photo": "https://m.media-amazon.com/images/I/61jv8Sj964L._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹119",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": false,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B08VN5YW3R",
          "product_title": "ZEBRONICS Zeb Duke 101 Wireless Headphone with Mic, Supporting Bluetooth 5.0, AUX Input Wired Mode, mSD Card Slot, Dual Pairing, On Ear &amp; 12 hrs Play Back time,FM, Media/Call Controls (Blue)",
          "product_price": "₹599",
          "product_original_price": "₹1,899",
          "currency": "INR",
          "product_star_rating": "3.4",
          "product_num_ratings": 1114,
          "product_url": "https://www.amazon.in/dp/B08VN5YW3R",
          "product_photo": "https://m.media-amazon.com/images/I/61WuZE2jqjL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹599",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        
      {
        "asin": "B08SFFP19B",
        "product_title": "pTron Pride Lite HBE (High Bass Earphones) in Ear Wired Earphones with Mic, 10mm Powerful Driver for Stereo Audio, Noise Cancelling Headset with 1.2m Tangle-Free Cable &amp; 3.5mm Aux - (Blue)",
        "product_price": "₹189",
        "product_original_price": "₹899",
        "currency": "INR",
        "product_star_rating": "3.5",
        "product_num_ratings": 59785,
        "product_url": "https://www.amazon.in/dp/B08SFFP19B",
        "product_photo": "https://m.media-amazon.com/images/I/51yB+3-eJwL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹189",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "2K+ bought in past month"
      },
      {
        "asin": "B01MF8MB65",
        "product_title": "boAt BassHeads 225 Special Edition in-Ear Wired Headphones with Mic (Blue)",
        "product_price": "₹499",
        "product_original_price": "₹999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 276412,
        "product_url": "https://www.amazon.in/dp/B01MF8MB65",
        "product_photo": "https://m.media-amazon.com/images/I/61fo5RouiZL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹499",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B08QTYYNDN",
        "product_title": "JBL Tune 510BT, On Ear Wireless Headphones with Mic, up to 40 Hours Playtime, Pure Bass, Quick Charging, Dual Pairing, Bluetooth 5.0 &amp; Voice Assistant Support for Mobile Phones (Black)",
        "product_price": "₹2,299",
        "product_original_price": "₹4,499",
        "currency": "INR",
        "product_star_rating": "3.8",
        "product_num_ratings": 43092,
        "product_url": "https://www.amazon.in/dp/B08QTYYNDN",
        "product_photo": "https://m.media-amazon.com/images/I/61kFL7ywsZS._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹2,299",
        "is_best_seller": true,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B01DF26V7A",
        "product_title": "JBL C100SI Wired In Ear Headphones with Mic, JBL Pure Bass Sound, One Button Multi-function Remote, Premium Metallic Finish, Angled Buds for Comfort fit (Red)",
        "product_price": "₹569",
        "product_original_price": "₹1,299",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 202238,
        "product_url": "https://www.amazon.in/dp/B01DF26V7A",
        "product_photo": "https://m.media-amazon.com/images/I/61Xoai3CG2L._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹569",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B09R24JBYV",
        "product_title": "ZEBRONICS Zeb-Bro in Ear Wired Earphones with Mic, 3.5mm Audio Jack, 10mm Drivers, Phone/Tablet Compatible(Green)",
        "product_price": "₹299",
        "product_original_price": "₹399",
        "currency": "INR",
        "product_star_rating": "3.5",
        "product_num_ratings": 39861,
        "product_url": "https://www.amazon.in/dp/B09R24JBYV",
        "product_photo": "https://m.media-amazon.com/images/I/61+0KSoFrOL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹299",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B09PV1DFNJ",
        "product_title": "ZEBRONICS Zeb-Bro in Ear Wired Earphones with Mic, 3.5mm Audio Jack, 10mm Drivers, Phone/Tablet Compatible(Red)",
        "product_price": "₹119",
        "product_original_price": "₹399",
        "currency": "INR",
        "product_star_rating": "3.5",
        "product_num_ratings": 39861,
        "product_url": "https://www.amazon.in/dp/B09PV1DFNJ",
        "product_photo": "https://m.media-amazon.com/images/I/61jv8Sj964L._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹119",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B07234XXJF",
        "product_title": "boAt BassHeads 100 in-Ear Wired Headphones with Mic (White)",
        "product_price": "₹349",
        "product_original_price": "₹999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 391812,
        "product_url": "https://www.amazon.in/dp/B07234XXJF",
        "product_photo": "https://m.media-amazon.com/images/I/71e1SSUhZeL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹349",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B071Z8M4KX",
        "product_title": "boAt BassHeads 100 in-Ear Wired Headphones with Mic (Black)",
        "product_price": "₹349",
        "product_original_price": "₹999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 391812,
        "product_url": "https://www.amazon.in/dp/B071Z8M4KX",
        "product_photo": "https://m.media-amazon.com/images/I/719elVA3FvL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹349",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B00SISEOLC",
        "product_title": "Sony Extra Bass MDR-XB450AP On-Ear Wired Headphones with Mic (Black)",
        "product_price": "₹2,099",
        "product_original_price": "₹2,490",
        "currency": "INR",
        "product_star_rating": "4.2",
        "product_num_ratings": 8680,
        "product_url": "https://www.amazon.in/dp/B00SISEOLC",
        "product_photo": "https://m.media-amazon.com/images/I/61t0HecIZbL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹2,099",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0C93KSD6B",
        "product_title": "Infinity - JBL Tranz 710, 72 Hrs Playtime with Quick Charge, Wireless On Ear Headphone with Mic, Deep Bass, Dual Equalizer, Bluetooth 5.0 with Voice Assistant Support (Black)",
        "product_price": "₹1,498",
        "product_original_price": "₹4,499",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 38261,
        "product_url": "https://www.amazon.in/dp/B0C93KSD6B",
        "product_photo": "https://m.media-amazon.com/images/I/716Il5U5F4L._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹1,498",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0BVRD5QKY",
        "product_title": "boAt Rockerz 558 Bluetooth Wireless Over Ear Headphones with Mic Upto 20 Hours Playback, 50MM Drivers, Soft Padded Ear Cushions and Physical Noise Isolation(Maroon Maverick)",
        "product_price": "₹1,999",
        "product_original_price": "₹4,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 61217,
        "product_url": "https://www.amazon.in/dp/B0BVRD5QKY",
        "product_photo": "https://m.media-amazon.com/images/I/61dPCezxNaL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹1,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B08TV2P1N8",
        "product_title": "boAt Rockerz 255 Pro+ Bluetooth in Ear Earphones with Upto 60 Hours Playback, ASAP Charge, IPX7, Dual Pairing and Bluetooth v5.0(Active Black)",
        "product_price": "₹999",
        "product_original_price": "₹3,990",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 171709,
        "product_url": "https://www.amazon.in/dp/B08TV2P1N8",
        "product_photo": "https://m.media-amazon.com/images/I/51aBTOiXRlL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B09TVVGXWS",
        "product_title": "OnePlus Bullets Z2 Bluetooth Wireless in Ear Earphones with Mic, Bombastic Bass - 12.4 Mm Drivers, 10 Mins Charge - 20 Hrs Music, 30 Hrs Battery Life (Magico Black)",
        "product_price": "₹1,999",
        "product_original_price": "₹2,299",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 134459,
        "product_url": "https://www.amazon.in/dp/B09TVVGXWS",
        "product_photo": "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹1,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "60K+ bought in past month"
      },
      {
        "asin": "B0B3MNYGTW",
        "product_title": "OnePlus Bullets Z2 Bluetooth Wireless in Ear Earphones with Mic, Bombastic Bass, 10 Mins Charge - 20 Hrs Music, 30 Hrs Battery Life (Acoustic Red)",
        "product_price": "₹1,999",
        "product_original_price": "₹2,299",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 134459,
        "product_url": "https://www.amazon.in/dp/B0B3MNYGTW",
        "product_photo": "https://m.media-amazon.com/images/I/5171kgKguGL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹1,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "20K+ bought in past month"
      },
      
      {
        "asin": "B091MC66JP",
        "product_title": "pTron Tangentbeat in-Ear Bluetooth Wireless Headphones with Mic, Punchy Bass, 10mm Drivers, Clear Calls, Dual Pairing, Fast Charging, Magnetic Buds, Voice Assist &amp; IPX4 Wireless Neckband (Dark Blue)",
        "product_price": "₹499",
        "product_original_price": "₹2,499",
        "currency": "INR",
        "product_star_rating": "3.8",
        "product_num_ratings": 84637,
        "product_url": "https://www.amazon.in/dp/B091MC66JP",
        "product_photo": "https://m.media-amazon.com/images/I/51P6DqgGnaS._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹499",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "6K+ bought in past month"
      },
      {
        "asin": "B00Y4ORQ46",
        "product_title": "Logitech H111 Wired On Ear Headphones With Mic Black",
        "product_price": "₹745",
        "product_original_price": "₹955",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 15876,
        "product_url": "https://www.amazon.in/dp/B00Y4ORQ46",
        "product_photo": "https://m.media-amazon.com/images/I/61HBpQuLjVL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹745",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B00KGZZ824",
        "product_title": "Sony MDR-ZX110A Wired On Ear Headphone without Mic (White)",
        "product_price": "₹799",
        "product_original_price": "₹1,390",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 51515,
        "product_url": "https://www.amazon.in/dp/B00KGZZ824",
        "product_photo": "https://m.media-amazon.com/images/I/41BoLKMYjnL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹799",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B098FKXT8L",
        "product_title": "Bose Quietcomfort 45 Bluetooth Wireless Over Ear Headphones with Mic Noise Cancelling - Triple Black",
        "product_price": "₹18,988",
        "product_original_price": "₹29,900",
        "currency": "INR",
        "product_star_rating": "4.4",
        "product_num_ratings": 18226,
        "product_url": "https://www.amazon.in/dp/B098FKXT8L",
        "product_photo": "https://m.media-amazon.com/images/I/51j7l0QISqL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹18,988",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B07JQKR35P",
        "product_title": "JBL C50HI, Wired in Ear Headphones with Mic, One Button Multi-Function Remote, Lightweight &amp; Comfortable fit (Blue)",
        "product_price": "₹449",
        "product_original_price": "₹999",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 104108,
        "product_url": "https://www.amazon.in/dp/B07JQKR35P",
        "product_photo": "https://m.media-amazon.com/images/I/512x0VZ9ZaL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹449",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B08D77XZX5",
        "product_title": "pTron Tangentbeat in-Ear Bluetooth 5.0 Wireless Headphones with Mic, Deep Bass, 10mm Drivers, Clear Calls, Dual Pairing, Fast Charging, Magnetic Buds, Voice Assistant &amp; IPX4 Wireless Neckband (Black",
        "product_price": "₹499",
        "product_original_price": "₹2,499",
        "currency": "INR",
        "product_star_rating": "3.8",
        "product_num_ratings": 84637,
        "product_url": "https://www.amazon.in/dp/B08D77XZX5",
        "product_photo": "https://m.media-amazon.com/images/I/51K8TkvtjgL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹499",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "8K+ bought in past month"
      },
      {
        "asin": "B09R24HMNW",
        "product_title": "ZEBRONICS Zeb-Bro in Ear Wired Earphones with Mic, 3.5mm Audio Jack, 10mm Drivers, Phone/Tablet Compatible(Blue)",
        "product_price": "₹119",
        "product_original_price": "₹399",
        "currency": "INR",
        "product_star_rating": "3.5",
        "product_num_ratings": 39861,
        "product_url": "https://www.amazon.in/dp/B09R24HMNW",
        "product_photo": "https://m.media-amazon.com/images/I/61+5q4oGJWL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹119",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0856HNMR7",
        "product_title": "boAt Rockerz 370 On Ear Bluetooth Headphones with Upto 12 Hours Playtime, Cozy Padded Earcups and Bluetooth v5.0, with Mic (Buoyant Black)",
        "product_price": null,
        "product_original_price": null,
        "currency": null,
        "product_star_rating": "4",
        "product_num_ratings": 37304,
        "product_url": "https://www.amazon.in/dp/B0856HNMR7",
        "product_photo": "https://m.media-amazon.com/images/I/61kWB+uzR2L._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": null,
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B08YYQ3WFG",
        "product_title": "boAt Bassheads 105 Wired in Ear Earphones with Mic (Black)",
        "product_price": "₹329",
        "product_original_price": "₹999",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 30730,
        "product_url": "https://www.amazon.in/dp/B08YYQ3WFG",
        "product_photo": "https://m.media-amazon.com/images/I/51PyI5qRSwS._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹329",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B09CYX92NB",
        "product_title": "JBL Tune 770NC Wireless Over Ear ANC Headphones with Mic, Upto 70 Hrs Playtime, Speedcharge, Google Fast Pair, Dual Pairing, BT 5.3 LE Audio, Customize on Headphones App (Black)",
        "product_price": "₹5,998",
        "product_original_price": "₹9,999",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 1215,
        "product_url": "https://www.amazon.in/dp/B09CYX92NB",
        "product_photo": "https://m.media-amazon.com/images/I/51waTVRK2+L._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹5,998",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B07KY3L8CR",
        "product_title": "boAt Bassheads 162 in Ear Wired Earphones with Mic(Raging Red)",
        "product_price": "₹399",
        "product_original_price": "₹1,299",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 37124,
        "product_url": "https://www.amazon.in/dp/B07KY3L8CR",
        "product_photo": "https://m.media-amazon.com/images/I/61fHJ9+1IWL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹399",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B07Q4QK379",
        "product_title": "Bose Noise Cancelling 700 Bluetooth Wireless Over Ear Headphones with Mic for Clear Calls &amp; Alexa Enabled and Touch Control, (Silver Luxe)",
        "product_price": "₹22,397",
        "product_original_price": "₹34,500",
        "currency": "INR",
        "product_star_rating": "4.3",
        "product_num_ratings": 41070,
        "product_url": "https://www.amazon.in/dp/B07Q4QK379",
        "product_photo": "https://m.media-amazon.com/images/I/41l1kjWk56L._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹22,397",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0B1PW53LT",
        "product_title": "Noise Two Wireless On-Ear Headphones with 50 Hours Playtime, Low Latency(up to 40ms), 4 Play Modes, Dual Pairing, BT v5.3 (Calm White)",
        "product_price": "₹2,099",
        "product_original_price": "₹4,999",
        "currency": "INR",
        "product_star_rating": "3.5",
        "product_num_ratings": 1335,
        "product_url": "https://www.amazon.in/dp/B0B1PW53LT",
        "product_photo": "https://m.media-amazon.com/images/I/51uz82iC95L._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹2,099",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B01DF29XFW",
        "product_title": "JBL C100SI Wired In Ear Headphones with Mic, JBL Pure Bass Sound, One Button Multi-function Remote, Angled Buds for Comfort fit (White)",
        "product_price": "₹569",
        "product_original_price": "₹1,299",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 202238,
        "product_url": "https://www.amazon.in/dp/B01DF29XFW",
        "product_photo": "https://m.media-amazon.com/images/I/51o8A6J6UbL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹569",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      }
    ]);

      // console.log(price);
      const handleSortByPrice = () => {
        const sortedProducts = [...products].sort((a, b) => {
          const priceA = Number((a.product_price || '').replace(/[^0-9.-]+/g, ''));
          const priceB = Number((b.product_price || '').replace(/[^0-9.-]+/g, ''));
          return priceA - priceB;
        });
        setProducts(sortedProducts);
      };
      const handleSortByPriceHigh = () => {
        const sortedProducts = [...products].sort((a, b) => {
          const priceA = Number((a.product_price || '').replace(/[^0-9.-]+/g, ''));
          const priceB = Number((b.product_price || '').replace(/[^0-9.-]+/g, ''));
          return priceB - priceA;
        });
        setProducts(sortedProducts);
      };
      
  return (
    <>
     <button className="cart-btn-sort" onClick={handleSortByPrice}>
        Sort by Price (Low to High)
      </button>
     <button className="cart-btn-high" onClick={handleSortByPriceHigh}>
        Sort by Price (High To Low)
      </button>
      {products.map((productItem, index) => (
        <div key={index} className="main1">
          <img
            className="headphone-image"
            src={productItem.product_photo}
            alt=""
          />
          <p>{productItem.product_title}</p>
          <p>Price: {productItem.product_price}</p>
          <p>Product Review: {productItem.product_num_ratings}</p>
          <p>Product Rating: {productItem.product_star_rating} Out Of 5</p>
          <p>More About Products:- <a className="link" href={productItem.product_url} target="_blank">Link</a></p>
          <button className="cart-btn" onClick={() => onAddToCart(productItem)}>Add Item</button>
        </div>
      ))}
      {/* })} */}
    </>
  );
}

export default Headphone;
