import React from 'react'
import { useState } from 'react';
import "./cart.css"

function Laptop({onAddToCart}) {
  const [products, setProducts] = useState([

        {
          "asin": "B0B5KTSVTG",
          "product_title": "Acer Aspire 5 Gaming Laptop Intel Core i5 12th gen (16 GB/512 GB SSD/Win11 Home/4GB Graphics/RTX 2050) A515-57G (15.6&quot; FHD Display, 1.8 Kg)",
          "product_price": "₹50,990",
          "product_original_price": "₹82,999",
          "currency": "INR",
          "product_star_rating": "4",
          "product_num_ratings": 716,
          "product_url": "https://www.amazon.in/dp/B0B5KTSVTG",
          "product_photo": "https://m.media-amazon.com/images/I/61xzutxSl8L._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹50,990",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0B6F5V23N",
          "product_title": "HP Laptop 15s, 12th Gen Intel Core i5-1235U, 15.6-inch (39.6 cm), FHD, 8GB DDR4, 512GB SSD, Intel Iris Xe Graphics, Backlit KB, Thin &amp; Light (Win 11, MSO 2021, Silver, 1.69 kg), fq5111TU",
          "product_price": "₹51,999",
          "product_original_price": "₹67,832",
          "currency": "INR",
          "product_star_rating": "4",
          "product_num_ratings": 650,
          "product_url": "https://www.amazon.in/dp/B0B6F5V23N",
          "product_photo": "https://m.media-amazon.com/images/I/716xIHNg32L._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹51,999",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0B4N77Y34",
          "product_title": "HP [SmartChoice] 15s, Ryzen 5-5500U, 16GB RAM/512GB SSD 15.6&quot;(39.6 cm) FHD Laptop/Alexa Built-in/Windows 11 /AMD Radeon Graphics/MSO 2021/1.69 Kg, eq2132au, eq2182au",
          "product_price": "₹43,486",
          "product_original_price": "₹59,109",
          "currency": "INR",
          "product_star_rating": "4.1",
          "product_num_ratings": 2184,
          "product_url": "https://www.amazon.in/dp/B0B4N77Y34",
          "product_photo": "https://m.media-amazon.com/images/I/71yjoXu2ZAL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹43,486",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0BP2M7CCS",
          "product_title": "HP Laptop 15s, 12th Gen Intel Core i3-1215U, 15.6-inch (39.6 cm), FHD, 8GB DDR4, 512GB SSD, Intel UHD Graphics, Backlit KB, Thin &amp; Light, Dual Speakers (Win 11, MSO 2021, Silver, 1.69 kg), fq5007TU",
          "product_price": "₹38,827",
          "product_original_price": "₹56,261",
          "currency": "INR",
          "product_star_rating": "4.1",
          "product_num_ratings": 1739,
          "product_url": "https://www.amazon.in/dp/B0BP2M7CCS",
          "product_photo": "https://m.media-amazon.com/images/I/71c+XxQTRgL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹38,827",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0CH39Y5W1",
          "product_title": "ASUS BR1100 Laptop, 11.6&quot; (29.46cm) HD Anti-Glare Display, Intel Celeron N4500, 8GB RAM, 128GB SSD, MIL-STD 810H Durability, Windows 10 Home, Dark Grey, BR1100CKA-GJ0746W",
          "product_price": "₹19,990",
          "product_original_price": "₹33,990",
          "currency": "INR",
          "product_star_rating": null,
          "product_num_ratings": 0,
          "product_url": "https://www.amazon.in/dp/B0CH39Y5W1",
          "product_photo": "https://m.media-amazon.com/images/I/71jjYEX-pFL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹19,990",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0CHVQ2SZQ",
          "product_title": "FUTOPIA Ultimus Lite Celeron Dual Core N4020 - (8 GB/256 GB SSD/Windows 11 Home) NU14U4INC54BN-CS Thin and Light Laptop (14.1 Inch, Cloud Silver)",
          "product_price": "₹14,990",
          "product_original_price": "₹35,990",
          "currency": "INR",
          "product_star_rating": "5",
          "product_num_ratings": 5,
          "product_url": "https://www.amazon.in/dp/B0CHVQ2SZQ",
          "product_photo": "https://m.media-amazon.com/images/I/51KDQYrnsIL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹14,990",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0C918JGBM",
          "product_title": "Dell G15 5520 Gaming Laptop, Intel i5-12500H/16GB DDR5/1TB SSD/15.6&quot; (39.62cm) FHD WVA AG 120Hz 250 nits/NVIDIA RTX 3050, 4 GB GDDR6/Win 11 + MSO&#x27;21/15 Months McAfee/Backlit KB/Dark Shadow Grey/2.81kg",
          "product_price": "₹72,990",
          "product_original_price": "₹93,211",
          "currency": "INR",
          "product_star_rating": "4",
          "product_num_ratings": 240,
          "product_url": "https://www.amazon.in/dp/B0C918JGBM",
          "product_photo": "https://m.media-amazon.com/images/I/51jUcRK69ML._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹72,990",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0CCYGC3TS",
          "product_title": "ASUS TUF Gaming F15, 15.6&quot;(39.62 cms) FHD 144Hz, Intel Core i7-11800H 11th Gen, 4GB NVIDIA GeForce RTX 3050 Ti, Gaming Laptop (16GB/512GB SSD/Windows 11/90WHrs Battery/Black/2.30 Kg), FX506HE-HN382W",
          "product_price": "₹69,990",
          "product_original_price": "₹97,990",
          "currency": "INR",
          "product_star_rating": "4.1",
          "product_num_ratings": 22,
          "product_url": "https://www.amazon.in/dp/B0CCYGC3TS",
          "product_photo": "https://m.media-amazon.com/images/I/81UWgnVKDBL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹69,990",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0CHJJZ9G8",
          "product_title": "Acer Nitro V Gaming Laptop 13th Gen Intel Core i5-13420H with RTX 4050 Graphics 6GB VRAM, 144Hz Display (16GB DDR5/512GB SSD/Windows 11 Home/Wi-Fi 6),15.6&quot;(39.6cms) FHD ANV15-51",
          "product_price": "₹73,990",
          "product_original_price": "₹92,999",
          "currency": "INR",
          "product_star_rating": "4.1",
          "product_num_ratings": 44,
          "product_url": "https://www.amazon.in/dp/B0CHJJZ9G8",
          "product_photo": "https://m.media-amazon.com/images/I/516qCPpFXkL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹73,990",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0C15BKF4G",
          "product_title": "Dell 14 Laptop, Intel Core i5-1135G7 Processor/ 8GB DDR4/ 512GB SSD/14.0&quot; (35.56cm) FHD Display with Comfort View/Windows 11 + MSO&#x27;21/ Spill-Resistant Keyboard/ 15 Month McAfee/ 1.48kg",
          "product_price": "₹43,990",
          "product_original_price": "₹69,211",
          "currency": "INR",
          "product_star_rating": "3.5",
          "product_num_ratings": 216,
          "product_url": "https://www.amazon.in/dp/B0C15BKF4G",
          "product_photo": "https://m.media-amazon.com/images/I/71EF8fY2HuL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹43,990",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0B4N6JVMW",
          "product_title": "HP Laptop 15s, 11th Gen Intel Core i3-1115G4, 15.6-inch (39.6 cm), FHD, 8GB DDR4, 512GB SSD, Intel UHD Graphics, Thin &amp; Light, Dual Speakers (Win 11, MSO 2021, Silver, 1.69 kg), fq2673TU",
          "product_price": "₹35,990",
          "product_original_price": "₹47,557",
          "currency": "INR",
          "product_star_rating": "4.1",
          "product_num_ratings": 1739,
          "product_url": "https://www.amazon.in/dp/B0B4N6JVMW",
          "product_photo": "https://m.media-amazon.com/images/I/71fSS6dVWzL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹35,990",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0C3CLH1PV",
          "product_title": "HP Laptop 15s, Intel Celeron, 15.6-inch (39.6 cm), HD, 8GB DDR4, 512GB SSD, Intel UHD Graphics, Thin &amp; Light, Dual Speakers, BrightView Display (Win 11, MSO 2021, Silver, 1.65 kg), fq3071TU",
          "product_price": "₹28,490",
          "product_original_price": "₹33,934.38",
          "currency": "INR",
          "product_star_rating": "3.3",
          "product_num_ratings": 73,
          "product_url": "https://www.amazon.in/dp/B0C3CLH1PV",
          "product_photo": "https://m.media-amazon.com/images/I/71q31+pLWaL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹28,490",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0BWJS72C1",
          "product_title": "MSI Titan GT77 HX, Intel 13th Gen. i9-13980HX, 44CM FHD 144Hz Mini LED, HDR 1000 Gaming Laptop (64GB/4TB NVMe SSD/Windows 11 Home/Nvidia GeForce RTX4090, 16GB GDDR6/Core Black/3.3Kg), 13VI-092IN",
          "product_price": "₹5,69,990",
          "product_original_price": "₹6,71,990",
          "currency": "INR",
          "product_star_rating": "3.2",
          "product_num_ratings": 12,
          "product_url": "https://www.amazon.in/dp/B0BWJS72C1",
          "product_photo": "https://m.media-amazon.com/images/I/71yWBoj2kuL._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹5,69,990",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        {
          "asin": "B0C8P8WBSJ",
          "product_title": "Acer Aspire Lite 11th Gen Intel Core i3 Premium Metal Laptop (8GB RAM/256GB SSD/Windows 11 Home) AL15-51, 39.62cm (15.6&quot;) Full HD Display, Metal Body, Steel Gray, 1.59 Kg",
          "product_price": "₹28,990",
          "product_original_price": "₹42,990",
          "currency": "INR",
          "product_star_rating": "3.9",
          "product_num_ratings": 186,
          "product_url": "https://www.amazon.in/dp/B0C8P8WBSJ",
          "product_photo": "https://m.media-amazon.com/images/I/71czGb00k5L._AC_SX444_SY639_QL65_.jpg",
          "product_num_offers": null,
          "product_minimum_offer_price": "₹28,990",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": null
        },
        
      {
        "asin": "B08N5XSG8Z",
        "product_title": "Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, 8GB RAM, 256GB SSD Storage, Backlit Keyboard, FaceTime HD Camera, Touch ID. Works with iPhone/iPad; Gold",
        "product_price": "₹69,990",
        "product_original_price": "₹99,900",
        "currency": "INR",
        "product_star_rating": "4.7",
        "product_num_ratings": 1502,
        "product_url": "https://www.amazon.in/dp/B08N5XSG8Z",
        "product_photo": "https://m.media-amazon.com/images/I/71vFKBpKakL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹69,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0C3CLH1PV",
        "product_title": "HP Laptop 15s, Intel Celeron, 15.6-inch (39.6 cm), HD, 8GB DDR4, 512GB SSD, Intel UHD Graphics, Thin &amp; Light, Dual Speakers, BrightView Display (Win 11, MSO 2021, Silver, 1.65 kg), fq3071TU",
        "product_price": "₹28,490",
        "product_original_price": "₹33,934.38",
        "currency": "INR",
        "product_star_rating": "3.3",
        "product_num_ratings": 73,
        "product_url": "https://www.amazon.in/dp/B0C3CLH1PV",
        "product_photo": "https://m.media-amazon.com/images/I/71q31+pLWaL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹28,490",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0C91QWF1X",
        "product_title": "Dell Inspiron 5430 Laptop, Intel Core i7-1360P Processor/ 16GB/ 1TB SSD/14.0&quot; (35.56cm) FHD+ WVA AG with Comfortview 250 nits/Backlit KB + FPR/Win 11 + MSO&#x27;21/15 Month McAfee/Platinum Silver/ 1.59kg",
        "product_price": "₹84,990",
        "product_original_price": "₹1,06,797",
        "currency": "INR",
        "product_star_rating": "3.1",
        "product_num_ratings": 38,
        "product_url": "https://www.amazon.in/dp/B0C91QWF1X",
        "product_photo": "https://m.media-amazon.com/images/I/71jI0AcBRjL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹84,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0BWJS72C1",
        "product_title": "MSI Titan GT77 HX, Intel 13th Gen. i9-13980HX, 44CM FHD 144Hz Mini LED, HDR 1000 Gaming Laptop (64GB/4TB NVMe SSD/Windows 11 Home/Nvidia GeForce RTX4090, 16GB GDDR6/Core Black/3.3Kg), 13VI-092IN",
        "product_price": "₹5,69,990",
        "product_original_price": "₹6,71,990",
        "currency": "INR",
        "product_star_rating": "3.2",
        "product_num_ratings": 12,
        "product_url": "https://www.amazon.in/dp/B0BWJS72C1",
        "product_photo": "https://m.media-amazon.com/images/I/71yWBoj2kuL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹5,69,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0B9YHX39M",
        "product_title": "Lenovo IdeaPad Slim 3 Intel Core i3-1115G4 11th Gen 15.6&quot; (39.62cm) FHD Laptop (8GB/256GB SSD/Win 11/Office 2021/3 Month Game Pass/Arctic Grey/1.65Kg), 82H803TXIN",
        "product_price": "₹32,490",
        "product_original_price": "₹49,190",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 422,
        "product_url": "https://www.amazon.in/dp/B0B9YHX39M",
        "product_photo": "https://m.media-amazon.com/images/I/512QAURU1TL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹32,490",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0BC9VHH9F",
        "product_title": "HONOR MagicBook 14, AMD Ryzen 5 5500U 14-inch (35.56 cm) FHD IPS Anti-Glare Thin and Light Laptop (8GB/512GB PCIe SSD/Windows 11/Fingerprint Login/Metal Body/Backlit KB/1.38Kg), Gray, NobelM-WDQ9BHNE",
        "product_price": "₹36,990",
        "product_original_price": "₹65,999",
        "currency": "INR",
        "product_star_rating": "4.2",
        "product_num_ratings": 401,
        "product_url": "https://www.amazon.in/dp/B0BC9VHH9F",
        "product_photo": "https://m.media-amazon.com/images/I/71tHNTGasKL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹36,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0BHZM89M6",
        "product_title": "Xiaomi Notebook Ultra Max 11th Gen Intel Core i5-11320H Thin &amp; Light (16GB/512GB SSD/Iris Xe Graphics/15.6&quot; 3.2K Resolution/Win 11/Thunderbolt 4/MS Office &#x27;21/Fingerprint Sensor/1.7 Kg)",
        "product_price": "₹46,990",
        "product_original_price": "₹76,999",
        "currency": "INR",
        "product_star_rating": "4.2",
        "product_num_ratings": 2161,
        "product_url": "https://www.amazon.in/dp/B0BHZM89M6",
        "product_photo": "https://m.media-amazon.com/images/I/710aJMxsUXL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹46,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B09KTR4PDS",
        "product_title": "Chuwi CoreBook X Laptop 14&#x27;&#x27;, Intel Core i3-1005G1, 8GB RAM 512GB SSD, Windows 11 Laptop, 1920x1200 FHD Display, Up to 3.4Ghz | WiFi 6 | Backlit Keyboard | Webcam | BT5.1 | Type-C",
        "product_price": "₹23,990",
        "product_original_price": "₹49,990",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 2033,
        "product_url": "https://www.amazon.in/dp/B09KTR4PDS",
        "product_photo": "https://m.media-amazon.com/images/I/51szHunq3kL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹23,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0CCDRPGD8",
        "product_title": "JioBook 11 (2023) NB1112MM(BLU) (Mediatek 8788 Octa-core 2 GHz/ARM Mali G72 MP3 @800 MHz/29.5cms 60 Hz/Thin and Light Laptop/ 4 GB LPDDR4/ 64 GB eMMC/JioOS 4G LTE, Dual Band Wi-Fi/Blue/ 990 GMS)",
        "product_price": "₹14,499",
        "product_original_price": "₹25,000",
        "currency": "INR",
        "product_star_rating": "3.1",
        "product_num_ratings": 118,
        "product_url": "https://www.amazon.in/dp/B0CCDRPGD8",
        "product_photo": "https://m.media-amazon.com/images/I/51cNQIk3q9L._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹14,499",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0CJBP38HR",
        "product_title": "HP Laptop 15, 12th Gen i5-1235U, 15.6-inch (39.6 cm), FHD, Anti-Glare, 8GB DDR4, 512GB SSD, Intel Iris Xᶱ Graphics, Backlit Keyboard, Dual Speakers, (Win 11, MSO 2021, Silver, 1.69 kg), 15s-fy5007TU",
        "product_price": "₹50,990",
        "product_original_price": "₹65,447",
        "currency": "INR",
        "product_star_rating": null,
        "product_num_ratings": 0,
        "product_url": "https://www.amazon.in/dp/B0CJBP38HR",
        "product_photo": "https://m.media-amazon.com/images/I/71J17FvBvtL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹50,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0BM45QW4L",
        "product_title": "HP 245 G8 AMD Ryzen 3-3250 HD Notebook Business Laptop 14inch (35.6cm) (4 GB RAM / 1TB HDD/Windows 11 Home) 1 Year Warranty",
        "product_price": "₹22,990",
        "product_original_price": "₹39,600",
        "currency": "INR",
        "product_star_rating": "3",
        "product_num_ratings": 154,
        "product_url": "https://www.amazon.in/dp/B0BM45QW4L",
        "product_photo": "https://m.media-amazon.com/images/I/41SkKjJoWwL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹22,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B09QQM3J65",
        "product_title": "HP Chromebook X360,Intel Celeron N4120,14-Inch (35.6 Cm),Hd,4Gb Lpddr4,64Gb Emmc,Intel Uhd Graphics,Thin&amp;Light,Dual Speakers,Brightview Display (Chrome 64,White,1.49 Kg),Ca0505Tu,Chrome OS",
        "product_price": "₹22,990",
        "product_original_price": "₹32,295",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 221,
        "product_url": "https://www.amazon.in/dp/B09QQM3J65",
        "product_photo": "https://m.media-amazon.com/images/I/619nJDbUDkL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹22,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0C2HZYM87",
        "product_title": "HP Victus Gaming Laptop, 12th Gen Intel Core i5-12450H, NVIDIA RTX 3050 GPU, 15.6-inch (39.6 cm), FHD, IPS, 144Hz, 9 ms Response time, 16GB DDR4, 512GB SSD, Backlit KB (MSO, Blue, 2.29 kg) fa0666TX",
        "product_price": "₹68,990",
        "product_original_price": "₹86,343",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 149,
        "product_url": "https://www.amazon.in/dp/B0C2HZYM87",
        "product_photo": "https://m.media-amazon.com/images/I/71h9nOTd93L._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹68,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0BQSH511C",
        "product_title": "ASUS Vivobook Go 15 (2023), AMD Ryzen 5 7520U, 15.6&quot; (39.62 cm) FHD, Thin and Light Laptop (16GB/512GB SSD/Integrated Graphics/Windows 11/Office 2021/Silver/1.8 Kg), E1504FA-NJ541WS",
        "product_price": "₹43,549",
        "product_original_price": "₹70,990",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 36,
        "product_url": "https://www.amazon.in/dp/B0BQSH511C",
        "product_photo": "https://m.media-amazon.com/images/I/61m5Zo-2A1L._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹43,549",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0CFYG8J2C",
        "product_title": "(Refurbished) Lenovo V15 Intel Celeron N4020 15.6&quot; (39.62 cm) FHD 220 nits Antiglare Thin and Light Laptop (4GB RAM/1TB HDD/DOS/Iron Grey/1.85 kg), 82C30052IH",
        "product_price": "₹18,799",
        "product_original_price": "₹54,999",
        "currency": "INR",
        "product_star_rating": null,
        "product_num_ratings": 0,
        "product_url": "https://www.amazon.in/dp/B0CFYG8J2C",
        "product_photo": "https://m.media-amazon.com/images/I/61koe2VO+jL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹18,799",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      
      {
        "asin": "B0BVW7Q41W",
        "product_title": "Samsung Galaxy Book3 Core i7 13th Gen 1355U - (16 GB/512 GB SSD/Windows 11 Home) Galaxy Book3 Thin and Light Laptop (15.6 Inch, Graphite, 1.58 Kg, with MS Office)",
        "product_price": "₹84,990",
        "product_original_price": "₹1,12,990",
        "currency": "INR",
        "product_star_rating": "4.3",
        "product_num_ratings": 9,
        "product_url": "https://www.amazon.in/dp/B0BVW7Q41W",
        "product_photo": "https://m.media-amazon.com/images/I/71S4rL6SedL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹84,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0CDG7T8NF",
        "product_title": "HP Victus Gaming Laptop, AMD Ryzen 5 5600H, AMD Radeon RX 6500M Graphics, 15.6-inch (39.6 cm), FHD, IPS, 144Hz, 9 ms Response time, 8GB DDR4, 512GB SSD, Backlit KB (Win 11, Silver, 2.29 kg), fb0158AX",
        "product_price": "₹49,990",
        "product_original_price": "₹64,841",
        "currency": "INR",
        "product_star_rating": null,
        "product_num_ratings": 0,
        "product_url": "https://www.amazon.in/dp/B0CDG7T8NF",
        "product_photo": "https://m.media-amazon.com/images/I/71ds9lpXLnL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹49,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0CJ7Y8FQX",
        "product_title": "HP [SmartChoice 14s 11th Gen Intel i3 14 inches FHD, IPS (8GB RAM/ 512 GB SSD/LTE/Backlit Keyboard/UHD Graphics/Dual Speakers/Windows 11 Home/MS Office/1.49 Kg), 14s-ef1002tu, Natural Silver",
        "product_price": "₹36,990",
        "product_original_price": "₹54,552",
        "currency": "INR",
        "product_star_rating": "4.2",
        "product_num_ratings": 56,
        "product_url": "https://www.amazon.in/dp/B0CJ7Y8FQX",
        "product_photo": "https://m.media-amazon.com/images/I/71sdFTqRz6L._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹36,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0CKLN7PSZ",
        "product_title": "Acer Aspire Lite 12th Gen Intel Core i3-1215U Premium Metal Laptop (8GB RAM/512GB SSD/Windows 11 Home) AL15-51, 39.62cm (15.6&quot;) Full HD Display, Metal Body, Steel Gray, 1.59 Kg",
        "product_price": "₹31,990",
        "product_original_price": "₹52,990",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 186,
        "product_url": "https://www.amazon.in/dp/B0CKLN7PSZ",
        "product_photo": "https://m.media-amazon.com/images/I/617rprfdhRL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹31,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0B42QJMJP",
        "product_title": "Acer [SmartChoice] One 14 Business Laptop AMD Ryzen 3 3250U Processor (8GB RAM/256GB SSD/AMD Radeon Graphics/Windows 11 Home) Z2-493 with 35.56 cm (14.0&quot;) HD Display",
        "product_price": "₹23,990",
        "product_original_price": "₹38,999",
        "currency": "INR",
        "product_star_rating": "3.7",
        "product_num_ratings": 198,
        "product_url": "https://www.amazon.in/dp/B0B42QJMJP",
        "product_photo": "https://m.media-amazon.com/images/I/71LVd5vKMfL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹23,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B09SGGB687",
        "product_title": "ASUS VivoBook 15 (2021), 15.6-inch (39.62 cm) HD, Dual Core Intel Celeron N4020, Thin and Light Laptop (4GB RAM/256GB SSD/Integrated Graphics/Windows 11 Home/Transparent Silver/1.8 Kg), X515MA-BR011W",
        "product_price": "₹25,990",
        "product_original_price": "₹33,990",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 1120,
        "product_url": "https://www.amazon.in/dp/B09SGGB687",
        "product_photo": "https://m.media-amazon.com/images/I/71lYhcc++AL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹25,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0CGJJDF9J",
        "product_title": "HP Laptop 15s, Ryzen 5 5500U, 15.6-inch (39.6 cm) FHD, Anti-Glare, 16GB DDR4, 512GB SSD, AMD Radeon Graphics, Dual Speakers, Backlit KB (Win 11,MSO, Natural Silver, 1.69 kg), 15s-eq2132au",
        "product_price": "₹42,990",
        "product_original_price": "₹54,479",
        "currency": "INR",
        "product_star_rating": "3.6",
        "product_num_ratings": 49,
        "product_url": "https://www.amazon.in/dp/B0CGJJDF9J",
        "product_photo": "https://m.media-amazon.com/images/I/7151VAWe3RL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹42,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B09VPMHSJ6",
        "product_title": "ASUS BR1100 Notebook 12 (2022), 11.6-inch HD, Intel Celeron N4500, (4GB RAM/128GB M.2 NVMe™ PCIe®/Integrated Graphics/Windows 11 Home/Star Grey/1.26 Kg), BR1100CKA-GJ0722W",
        "product_price": "₹17,990",
        "product_original_price": "₹30,990",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 131,
        "product_url": "https://www.amazon.in/dp/B09VPMHSJ6",
        "product_photo": "https://m.media-amazon.com/images/I/71jjYEX-pFL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹17,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0C3RDM59N",
        "product_title": "HP Laptop 15s, 11th Gen Intel Core i5-1155G7, 15.6-inch (39.6 cm), FHD, 16GB DDR4, 512GB SSD, Intel Iris Xe Graphics, Backlit KB, Thin &amp; Light (Win 11, MSO 2021, Silver, 1.69 kg), fr4001TU",
        "product_price": "₹49,899",
        "product_original_price": "₹59,327",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 262,
        "product_url": "https://www.amazon.in/dp/B0C3RDM59N",
        "product_photo": "https://m.media-amazon.com/images/I/71fXlFIFMWL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹49,899",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0CFVYSZFG",
        "product_title": "ASUS Vivobook 16, Intel®Core™ i3-1215U 12th Gen, 16-inch (40.64 cm) FHD+, Thin and Light Laptop (8 GB RAM/512GB SSD/Win11/FingerPrint/Black/1.88kg), X1605ZAB-MB322WS",
        "product_price": "₹43,990",
        "product_original_price": "₹55,990",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 313,
        "product_url": "https://www.amazon.in/dp/B0CFVYSZFG",
        "product_photo": "https://m.media-amazon.com/images/I/71p1GQQCCWL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹43,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0C91QWF1X",
        "product_title": "Dell Inspiron 5430 Laptop, Intel Core i7-1360P Processor/ 16GB/ 1TB SSD/14.0&quot; (35.56cm) FHD+ WVA AG with Comfortview 250 nits/Backlit KB + FPR/Win 11 + MSO&#x27;21/15 Month McAfee/Platinum Silver/ 1.59kg",
        "product_price": "₹84,990",
        "product_original_price": "₹1,06,797",
        "currency": "INR",
        "product_star_rating": "3.1",
        "product_num_ratings": 38,
        "product_url": "https://www.amazon.in/dp/B0C91QWF1X",
        "product_photo": "https://m.media-amazon.com/images/I/71jI0AcBRjL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹84,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0CJBP38HR",
        "product_title": "HP Laptop 15, 12th Gen i5-1235U, 15.6-inch (39.6 cm), FHD, Anti-Glare, 8GB DDR4, 512GB SSD, Intel Iris Xᶱ Graphics, Backlit Keyboard, Dual Speakers, (Win 11, MSO 2021, Silver, 1.69 kg), 15s-fy5007TU",
        "product_price": "₹50,990",
        "product_original_price": "₹65,447",
        "currency": "INR",
        "product_star_rating": null,
        "product_num_ratings": 0,
        "product_url": "https://www.amazon.in/dp/B0CJBP38HR",
        "product_photo": "https://m.media-amazon.com/images/I/71J17FvBvtL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹50,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0CCP9RSG9",
        "product_title": "ASUS Vivobook 15, IntelCore i7-12650H 12th Gen, 15.6&quot; (39.62 cm) FHD, Thin and Light Laptop (16 GB RAM/512GB SSD/Win11/Office 2021/Backlit/42WHr /Silver/1.75), X1502ZA-EJ742WS",
        "product_price": "₹64,990",
        "product_original_price": "₹80,990",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 305,
        "product_url": "https://www.amazon.in/dp/B0CCP9RSG9",
        "product_photo": "https://m.media-amazon.com/images/I/813-FmU7N1L._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹64,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
      {
        "asin": "B0BVW75CSZ",
        "product_title": "Samsung Galaxy Book3 Core i7 13th Gen 1355U - (16 GB/512 GB SSD/Windows 11 Home) Galaxy Book3 Thin and Light Laptop (15.6 Inch, Silver, 1.58 Kg, with MS Office)",
        "product_price": "₹84,890",
        "product_original_price": "₹1,12,990",
        "currency": "INR",
        "product_star_rating": "4.3",
        "product_num_ratings": 9,
        "product_url": "https://www.amazon.in/dp/B0BVW75CSZ",
        "product_photo": "https://m.media-amazon.com/images/I/816fTYVn5lL._AC_SX444_SY639_QL65_.jpg",
        "product_num_offers": null,
        "product_minimum_offer_price": "₹84,890",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null
      },
    ]);

 const handleSortByPrice = () => {
        const sortedProducts = [...products].sort((a, b) => {
          const priceA = Number((a.product_price || '').replace(/[^0-9.-]+/g, ''));
          const priceB = Number((b.product_price || '').replace(/[^0-9.-]+/g, ''));
          return priceA - priceB;
        });
        setProducts(sortedProducts);
      };
      const handleSortByPriceHigh = () => {
        const sortedProducts = [...products].sort((a, b) => {
          const priceA = Number((a.product_price || '').replace(/[^0-9.-]+/g, ''));
          const priceB = Number((b.product_price || '').replace(/[^0-9.-]+/g, ''));
          return priceB - priceA;
        });
        setProducts(sortedProducts);
      };
      
  return (
    <>
     <button className="cart-btn-sort" onClick={handleSortByPrice}>
        Sort by Price (Low to High)
      </button>
     <button className="cart-btn-high" onClick={handleSortByPriceHigh}>
        Sort by Price (High To Low)
      </button>
    {products.map((productItem, index) => (
      <div key={index} className="main1">
        <img
          className="laptop-image"
          src={productItem.product_photo}
          alt=""
        />
        <p>{productItem.product_title}</p>
        <p>Price: {productItem.product_price}</p>
        <p>Product Review: {productItem.product_num_ratings}</p>
        <p>Product Rating: {productItem.product_star_rating} Out Of 5</p>
        <p>More About Products:- <a className="link" href={productItem.product_url} target="_blank">Link</a></p>
        <button className="cart-btn" onClick={() => onAddToCart(productItem)}>Add Item</button>
        {/* <button className="cart-btn" onClick={() => onRemoveToCart(productItem)}>Remove Item</button> */}
      </div>
    ))}
    {/* })} */}
  </>
  )
}

export default Laptop